version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: node:10.19.0
    steps:
      - checkout
      - restore_cache:
          key: yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    working_directory: ~/repo
    docker:
      - image: node:10.19.0
    steps:
      - attach_workspace:
          at: .
      - run: yarn lint
  docs:
    working_directory: ~/repo
    docker:
      - image: node:10.19.0
    steps:
      - attach_workspace:
          at: .
      - run: yarn build-storybook
      - store_artifacts:
          path: .tmp/storybook
  deploy:
    working_directory: ~/repo
    docker:
      - image: node:10.19.0
    steps:
      - attach_workspace:
          at: .
      - run: cd functions && npm install
      - run: yarn deploy --token=$FIREBASE_TOKEN

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - docs:
          requires:
            - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
